[book]
authors = ["非虫", "missingkeys"]
language = "zh-CN"
multilingual = false
src = "."
title = "安卓系统定制：从入门到实践"
description = "这是一本开源的讲解安卓系统定制入门的电子书"
version = "1.0.0"

[output.html]
git-repository-url = "https://github.com/feicong/rom-course"

[output.pdf]

# 添加页眉页脚
display-header-footer= true
header-template = "<h3 style='font-size:10px; margin-left: 85px;width:200px;' class='date'></h3><h3 style='margin-left:80px;font-size:10px;'>https://github.com/feicong/rom-course</h3>"
footer-template = "<p style='font-size:10px; margin-left: 88%'><span class='pageNumber'></span> / <span class='totalPages'></span></p>"
prefer-css-page-size = true

[output.pdf-outline]
like-wkhtmltopdf = true
